[window]
opacity = 0.9
startup_mode = "Maximized"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font]
size = 14

[[keyboard.bindings]]
key = "["
mods = "Control"
chars = "\u001b"
