theme = "gruvbox_dark_hard"

[editor]
scrolloff = 10
cursorline = true
auto-save = true
idle-timeout = 0
completion-trigger-len = 1
bufferline = "always"
true-color = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "┆"
skip-levels = 1

[editor.statusline]
left = ["mode", "version-control"]
center = ["spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
